name: zottz_flutter
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.31.15
  rename_app: ^1.6.2

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
